// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1660794595);
user_pref("app.update.lastUpdateTime.region-update-timer", 1660794835);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1660794355);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1660794475);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1660794385);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1660794715);
user_pref("browser.region.update.updated", 1660794329);
user_pref("browser.search.region", "SV");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "America/El_Salvador");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1660794337363");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1660794596);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220628000715");
user_pref("extensions.lastAppVersion", "91.11.0");
user_pref("extensions.lastPlatformVersion", "91.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"94c9c12e-c91e-476a-80f1-6fcf08e0dd3f\",\"google@search.mozilla.org\":\"f87a040d-746f-445c-9b0c-717befb3fa59\",\"ddg@search.mozilla.org\":\"3dae18f2-2158-467a-95b0-efb2d7f36483\",\"wikipedia@search.mozilla.org\":\"bd23cd4e-6046-413e-a4cc-bd7b129c01fe\",\"bing@search.mozilla.org\":\"0f4fb602-577b-4827-8722-6b323eaab17c\",\"drae@search.mozilla.org\":\"8919fece-4230-48b9-b833-ea627e404c12\"}");
user_pref("idle.lastDailyNotification", 1660794509);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 32);
user_pref("mailnews.database.global.datastore.id", "7dca2f01-5f33-4bb3-b1fc-4c70c149d92");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1660794509);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -45385);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1660839859);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1660839859);
user_pref("services.settings.thunderbird.search-config.last_check", 1660839859);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1660839859);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1660794509);
user_pref("toolkit.telemetry.cachedClientID", "520c7bcb-6b25-4b40-a4b0-77e05186db5d");
user_pref("toolkit.telemetry.previousBuildID", "20220628000715");
